### ISSUE TITLE
Various bugs on latest iteration

### ISSUE THREAD

**Issue by pwalsh** [okfn/datapackagist#190]
* [x] Error in js on page load

```
Unhandled rejection TypeError: Cannot read property 'css' of null
    at c.adjustBackdrop (http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js:6:17463)
    at c.handleUpdate (http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js:6:17373)
    at HTMLDivElement.<anonymous> (http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js:6:13612)
    at Function.jQuery.extend.each (http://127.0.0.1:3000/vendor.min.js:100748:23)
    at jQuery.fn.jQuery.each (http://127.0.0.1:3000/vendor.min.js:100513:17)
    at b [as modal] (http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js:6:13443)
    at http://127.0.0.1:3000/app.min.js:661:15
    at tryCatcher (http://127.0.0.1:3000/vendor.min.js:4557:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:3000/vendor.min.js:2659:31)
    at Promise._settlePromiseAt (http://127.0.0.1:3000/vendor.min.js:2733:18)
    at Promise._settlePromises (http://127.0.0.1:3000/vendor.min.js:2849:14)
    at Async._drainQueue (http://127.0.0.1:3000/vendor.min.js:147:16)
    at Async._drainQueues (http://127.0.0.1:3000/vendor.min.js:157:10)
    at Async.drainQueues (http://127.0.0.1:3000/vendor.min.js:39:14)
```

* [x] Error when when adding a CSV file using the "Upload data file" action in the form

```
Unhandled rejection TypeError: editor.add is not a function
    at backbone.BaseView.extend.addResource (http://127.0.0.1:3000/app.min.js:191:12)
    at null.<anonymous> (http://127.0.0.1:3000/app.min.js:205:26)
    at tryCatcher (http://127.0.0.1:3000/vendor.min.js:4557:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:3000/vendor.min.js:2659:31)
    at Promise._settlePromiseAt (http://127.0.0.1:3000/vendor.min.js:2733:18)
    at Promise._settlePromises (http://127.0.0.1:3000/vendor.min.js:2849:14)
    at Async._drainQueue (http://127.0.0.1:3000/vendor.min.js:147:16)
    at Async._drainQueues (http://127.0.0.1:3000/vendor.min.js:157:10)
    at Async.drainQueues (http://127.0.0.1:3000/vendor.min.js:39:14)
```

* [x] In section 1, when adding a `datapackage.json`, IF the JSON is found invalid, the UI state still shows that a data package has been selected
* [x] In section 1, if a valid `datapackage.json` is added, which has extra fields that are not in the spec explicitly, it is considered an error. However, this is incorrect - the spec allows for the use of additional properties on the descriptor, and `json-editor` also has the `no_additional_properties` API to allow this (https://github.com/jdorn/json-editor#options)
* [x] In section 1, if adding a file from local system, and the state changes to indicate a file has been added, it  shows the repr of the object, rather than the name of the file
* [x] In section 2, when selecting a new profile, the form does not *seem* to update. Please confirm that that form updates based on the selected profile
* [x] The `name`/`title` tracking does not force the auto-generated titles to Title Case
* [x] The "add resources" link in the text of section 3 is supposed to trigger the same action as the "Upload data file" button in the resources section of the form, but it currently does not
* [x] If I create a simple, valid data package (just add a name for the default data package profile), and then click the "download" link in the text under section 3, it tells me the package is not valid. However, if I click validate and *then* download, it always me to download. Seeing as the "download" action should always trigger a validate, and then allow a download if the file is valid, there is a weird bug here.
* [x] If I click "validate" either the bottom button or the link in section three, and the package is valid, nothing happens this is bad UX. I should receive a modal that says "The Data Package is valid."

**Comment by borysyuk** [comment]
https://github.com/okfn/datapackagist/pull/192

**Comment by pwalsh** [comment]
@borysyuk great work! thanks.
